use_frameworks!

platform :ios, '8.0'

target 'PTLibrary_Example' do
  pod 'PTLibrary', :path => '../'

  target 'PTLibrary_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
